/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import java.awt.*;

/**
 *
 * @author jk218
 */
public class GUI2 extends javax.swing.JFrame {

    /**
     * Creates new form GUI2
     */
    public GUI2() {
        initComponents();
        setLocationRelativeTo(rootPane);
        setTitle("Hamming Codes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        probabilityText = new javax.swing.JTextField();
        probabilityLabel = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        generateCodeLabel = new javax.swing.JLabel();
        probabilityLabel1 = new javax.swing.JLabel();
        codeLength = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        createdMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        probabilityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probabilityTextActionPerformed(evt);
            }
        });

        probabilityLabel.setText("Error probability");

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        generateCodeLabel.setText("Generated code");

        probabilityLabel1.setText("Length of Code");

        createdMessage.setColumns(20);
        createdMessage.setRows(5);
        jScrollPane1.setViewportView(createdMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(probabilityLabel)
                            .addGap(18, 18, 18)
                            .addComponent(probabilityText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(probabilityLabel1)
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(codeLength))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(generateCodeLabel)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(probabilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(probabilityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(probabilityLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(goButton)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(generateCodeLabel)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void probabilityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probabilityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_probabilityTextActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        dialog.setVisible(false);
        JTable statsTable = new JTable();


        final Dimension SCREEN_DIMENSION = Toolkit.getDefaultToolkit().getScreenSize();

//I'd also make this static and final and insert them at the class definition
        int dialogWidth = SCREEN_DIMENSION.width / 4; //example; a quarter of the screen size
        int dialogHeight = SCREEN_DIMENSION.height / 4; //example

        int dialogX = SCREEN_DIMENSION.width / 2 - dialogWidth / 2; //position right in the middle of the screen
        int dialogY = SCREEN_DIMENSION.height / 2 - dialogHeight / 2;
//        dialog = new JDialog();
        dialog.setBounds(dialogX,dialogY,dialogWidth,dialogHeight);


        dialog.setTitle("Statistics");

        statsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {"2", null, null, null, null, null},
                        {"3", null, null, null, null, null},
                        {"4", null, null, null, null, null},
                        {"5", null, null, null, null, null},
                        {"6", null, null, null, null, null}
                },
                new String [] {
                        " R Value", "Uncorrected Bit Count", "Uncorrected Chunk Count", "Percentage bits uncorrected", "Percentage of Chunks Affected", "Information rate"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        statsTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int newDialogWidth =0;
        for(int i=0;i<statsTable.getColumnCount();i++){
            DefaultTableColumnModel colModel = (DefaultTableColumnModel) statsTable.getColumnModel();
            TableColumn col = colModel.getColumn(i);
            int width = 0;

            TableCellRenderer renderer = col.getHeaderRenderer();
            if (renderer == null) {
                renderer = statsTable.getTableHeader().getDefaultRenderer();
            }
            Component comp = renderer.getTableCellRendererComponent(statsTable, col.getHeaderValue(), false,
                    false, 0, 0);
            width = comp.getPreferredSize().width;
            col.setPreferredWidth(width+2);
            newDialogWidth+=width+2;
        }

        int height = 175;
        dialog.setMinimumSize(new Dimension(newDialogWidth+2,height));
        dialog.setMaximumSize(new Dimension(newDialogWidth+2,height));
        dialog.setPreferredSize(new Dimension(newDialogWidth+2,height));
        dialog.setSize(new Dimension(newDialogWidth+2,height));
//                dialog.get
        JScrollPane js = new JScrollPane();
        js.setViewportView(statsTable);
        dialog.add(js);
//        dialog.pack();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.setVisible(true);
    }//GEN-LAST:event_goButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner codeLength;
    private javax.swing.JTextArea createdMessage;
    private javax.swing.JLabel generateCodeLabel;
    private javax.swing.JButton goButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel probabilityLabel;
    private javax.swing.JLabel probabilityLabel1;
    private javax.swing.JTextField probabilityText;
    private JDialog dialog = new JDialog();
    // End of variables declaration//GEN-END:variables
}
